### ISSUE TITLE
[Suggestion] Add API access to the bot

### ISSUE THREAD

**Issue by ajhalili2006** [YouTwitFace/SpamBlockersBot#2]
As SpamWatch got its API support,  should we add API access for SpamBlockers so I can also integrate to [my instance of the Guard](https://glitch.com/edit/#!/watchdog-chat-guard) in Glitch. 

## Generating API Keys
The user should contact the bot in PMs and send `/apikey generate` with `User` access permission. After that, the bot will send the API key. 

Any fed admin or bot master can revoke,  generate and adjust permissions for each API key. 

## Permission Access in API
It should be lile in SpamWatch, where there are root users (aka bot master),  federation admins and, ordinary users. 

## API Wrappers? 
Maybe soom, but let Twitface think about it.

**Comment by vrumger** [comment]
Feel free to open a pull request.

**Comment by DragSama** [comment]
> As SpamWatch got its API support, should we add API access for SpamBlockers so I can also integrate to [my instance of the Guard](https://glitch.com/edit/#!/watchdog-chat-guard) in Glitch.
> 
> ## Generating API Keys
> The user should contact the bot in PMs and send `/apikey generate` with `User` access permission. After that, the bot will send the API key.
> 
> Any fed admin or bot master can revoke, generate and adjust permissions for each API key.
> 
> ## Permission Access in API
> It should be lile in SpamWatcj, where there are root users (aka bot master), federation admins and, ordinary users.
> 
> ## API Wrappers?
> Maybe soom, but let Twitface think about it.

"Spamwatcj"?

**Comment by ajhalili2006** [comment]
Before I can get started coding for the API access, what framework should we use for the webserver (Express.js preferred, but suggest some)? Should we use REST API or GraphQL for the API?

**Comment by vrumger** [comment]
I prefer Express with a REST API. If you have any other questions we can talk on Telegram. :)

**Comment by ajhalili2006** [comment]
> I prefer Express with a REST API. If you have any other questions we can talk on Telegram. :)

Should the code for the API place it in `index.js` or a separate file?

**Comment by vrumger** [comment]
A separate file would probably make more sense in this case.

**Comment by vrumger** [comment]
I've created [SpamBlockers/api](https://github.com/SpamBlockers/api).
